build:
  environment:
    php: 7.2
  dependencies:
    before:
      - 'composer require typo3/minimal="^9"'
  nodes:
    analysis:
      cache:
        disabled: false
        directories:
          - ~/.composer/cache
      tests:
        override:
          - php-scrutinizer-run
          - js-scrutinizer-run
  tests:
    override:
      -
        command: './.build/bin/phpunit -c Build/UnitTests.xml --coverage-clover=coverage'
        coverage:
          file: 'coverage'
          format: 'clover'


filter:
  excluded_paths:
    - ".build/"

checks:
  javascript: true
  php:
    code_rating: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    verify_property_names: true
    verify_argument_usable_as_reference: true

tools:
  external_code_coverage:
    enabled: false

  php_cpd:
    enabled: true

  php_cs_fixer:
    enabled: true
    config:
      level: psr2

  php_hhvm:
    enabled: true
    config:
      use_undeclared_constant:  false

  php_mess_detector:
    enabled: true
    config:
      controversial_rules:
        superglobals: false

  php_pdepend:
    enabled: true

  php_analyzer:
    enabled: false

  php_code_coverage:
    enabled: false

  sensiolabs_security_checker:
    enabled: true
